<div class="widget-fluid" id="message-div">
    <form method="post">
        <div class="row-form">
            <span>Text:</span>
            <input type="text" placeholder="Placeholder example"/>
        </div>
        <div class="row-form">
            <input type="checkbox" checked="checked" value="1"/>Checked
            <input type="checkbox" value="2"/>Unchecked
        </div>
        <div class="row-form">
            <select>
                <option value="0">0</option>
                <option value="1">1</option>
                <option value="2">2</option>
            </select>
        </div>
        <div class="row-form">
            <span>Tags</span>
            <input class="tags" value="PHP,CSS"/>
        </div>
        <div class="row-form">
            <textarea name="text"></textarea>
        </div>
        <div class="row-form TAR">
            <button class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>