<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'admin/index/index'                     => __DIR__ . '/view/admin/index/index.phtml',
    'error/404'                             => __DIR__ . '/view/error/404.phtml',
    'error/index'                           => __DIR__ . '/view/error/index.phtml',
    'layout/header'                         => __DIR__ . '/view/layout/header.phtml',
    'layout/partials/internal-message-form' => __DIR__ . '/view/layout/partials/internal-message-form.phtml',
    'layout/partials/please-wait'           => __DIR__ . '/view/layout/partials/please-wait.phtml',
    'layout/partials/user-message'          => __DIR__ . '/view/layout/partials/user-message.phtml',
    'layout/sidebar'                        => __DIR__ . '/view/layout/sidebar.phtml',
    'layout/layout'                         => __DIR__ . '/view/layout/virgo.phtml',
    'layout/virgo/breadcrumb'               => __DIR__ . '/view/layout/virgo/breadcrumb.phtml',
    'layout/virgo/header'                   => __DIR__ . '/view/layout/virgo/header.phtml',
    'layout/virgo/navigation'               => __DIR__ . '/view/layout/virgo/navigation.phtml',
    'layout/virgo/quick-navigation'         => __DIR__ . '/view/layout/virgo/quick-navigation.phtml',
    'layout/virgo'                          => __DIR__ . '/view/layout/virgo.phtml',
);
