<?php
if ($grids) {
    $first = current($grids);
    $first->getJsCode()->addCustomScript(
        new \Zend\Json\Expr(";jQuery('.grid-tabs').on('shown', function(){ jQuery(window).trigger('resize');   }); "
        )
    );
}
?>
<div class="widget" id="menu-grid">
    <div class="head dark">
        <div class="icon"><i class="icos-list"></i></div>
        <h2>Page Builder</h2>
        <span class="wait-image pull-right"><img src="/img/loaders/1d_5.gif"/></span>
    </div>
    <div class="block-fluid tabbable">
        <ul class="nav nav-tabs grid-tabs">
            <?php
            $count = 0;
            foreach ($entities as $item) {
                $active = ($count++ == 0) ? 'active' : '';
                printf('<li class="%s"><a href="#g%s" data-toggle="tab">%s</a></li>', $active, $item, ucwords($item));
            }
            ?>
        </ul>

        <div class="tab-content">
            <?php
            $count = 0;
            foreach ($grids as $item => $grid) {
                $active = ($count++ == 0) ? ' active' : '';
                printf('<div class="tab-pane%s" id="g%s">%s</div>', $active, $item, $this->displayGrid($grid));
            }
            ?>
        </div>
    </div>
</div>