<a href="<?php echo $this->url('admin'); ?>" class="logo"></a>

<div class="buttons">

    <div class="popup" id="subNavControll">
        <div class="label"><span class="icos-list"></span></div>
    </div>
    <div class="dropdown">
        <div class="label"><span class="icos-user2"></span></div>
        <div class="body" style="width: 160px;">
            <div class="itemLink">
                <a href="#"><span class="icon-cog icon-white"></span> Settings</a>
            </div>
            <div class="itemLink">
                <a href="#"><span class="icon-comment icon-white"></span> Messages</a>
            </div>
            <div class="itemLink">
                <a href="<?php echo $this->url('home', array('action' => 'logout')); ?>"><span class="icon-off icon-white"></span>
                    Logout</a>
            </div>
        </div>
    </div>
    <div class="popup">
        <div class="label"><span class="icos-search1"></span></div>
        <div class="body">
            <div class="arrow"></div>
            <div class="row-fluid">
                <div class="row-form">
                    <div class="span12">
                        <div class="input-append input-prepend">
                            <span class="add-on"><i class="icon-search"></i></span>
                            <input type="text" name="search" placeholder="Keyword..."/>
                            <button class="btn" type="button">Search</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="popup">
        <div class="label"><span class="icos-cog"></span></div>
        <div class="body">
            <div class="arrow"></div>
            <div class="row-fluid">
                <div class="row-form">
                    <div class="span12">
                        <span class="top">Themes:</span>

                        <div class="themes">
                            <a href="#" data-theme="" class="tip" title="Default"><img src="/img/themes/default.jpg"/></a>
                            <a href="#" data-theme="ssDaB" class="tip" title="DaB"><img src="/img/themes/dab.jpg"/></a>
                            <a href="#" data-theme="ssTq" class="tip" title="Tq"><img src="/img/themes/tq.jpg"/></a>
                            <a href="#" data-theme="ssGy" class="tip" title="Gy"><img src="/img/themes/gy.jpg"/></a>
                            <a href="#" data-theme="ssLight" class="tip" title="Light"><img src="/img/themes/light.jpg"/></a>
                            <a href="#" data-theme="ssDark" class="tip" title="Dark"><img src="/img/themes/dark.jpg"/></a>
                            <a href="#" data-theme="ssGreen" class="tip" title="Green"><img src="/img/themes/green.jpg"/></a>
                            <a href="#" data-theme="ssRed" class="tip" title="Red"><img src="/img/themes/red.jpg"/></a>
                        </div>
                    </div>
                </div>
                <div class="row-form">
                    <div class="span12">
                        <span class="top">Backgrounds:</span>

                        <div class="backgrounds">
                            <a href="#" data-background="bg_default" class="bg_default"></a>
                            <a href="#" data-background="bg_mgrid" class="bg_mgrid"></a>
                            <a href="#" data-background="bg_crosshatch" class="bg_crosshatch"></a>
                            <a href="#" data-background="bg_hatch" class="bg_hatch"></a>
                            <a href="#" data-background="bg_light_gray" class="bg_light_gray"></a>
                            <a href="#" data-background="bg_dark_gray" class="bg_dark_gray"></a>
                            <a href="#" data-background="bg_texture" class="bg_texture"></a>
                            <a href="#" data-background="bg_light_orange" class="bg_light_orange"></a>
                            <a href="#" data-background="bg_yellow_hatch" class="bg_yellow_hatch"></a>
                            <a href="#" data-background="bg_green_hatch" class="bg_green_hatch"></a>
                        </div>
                    </div>
                </div>
                <div class="row-form">
                    <div class="span12">
                        <span class="top">Navigation:</span>
                        <input type="radio" name="navigation" id="fixedNav"/> Fixed
                        <input type="radio" name="navigation" id="collapsedNav"/> Collapsible
                        <input type="radio" name="navigation" id="hiddenNav"/> Hidden
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>