<div class="middle">

    <div class="button">
        <a href="#">
            <span class="icomg-earth"></span>
            <span class="text">Quick Navigation</span>
        </a>
        <ul class="sub">
            <li><a href="/" class="tip" title="Dashborad"><span class="icon-home"></span></a></li>
            <li><a href="ui.html" class="tip" title="Roles"><span class="icon-user"></span></a></li>
            <li><a href="grid.html" class="tip" title="Permissons"><span class="icon-th"></span></a></li>
            <li><a href="widgets.html" class="tip" title="Widgets"><span class="icon-th-large"></span></a></li>
            <li><a href="buttons.html" class="tip" title="Buttons"><span class="icon-chevron-right"></span></a>
            </li>
            <li><a href="icons.html" class="tip" title="Icons"><span class="icon-fire"></span></a></li>
            <li>
                <a href="http://google.com/" class="tip" title="Google" target="_blank"><span class="icon-globe"></span></a>
            </li>
            <li>
                <a href="http://youtube.com/" class="tip" title="Youtube" target="_blank"><span class="icon-globe"></span></a>
            </li>
        </ul>
    </div>

    <div class="button">
        <a href="#">
            <span class="icomg-user2"></span>
            <span class="text">Affiliate</span>
        </a>
        <ul class="sub">
            <li><a href="users.html" class="tip" title="Feeds"><span class="icon-th-list"></span></a></li>
            <li><a href="ui.html" class="tip" title="Networks"><span class="icon-plus"></span></a></li>
            <li><a href="#" class="tip" title="Skyscraper Ads"><span class="icon-ok"></span></a></li>
            <li><a href="#" class="tip" title="Banners"><span class="icon-envelope"></span></a></li>
            <li><a href="#" class="tip" title="Categories"><span class="icon-star"></span></a></li>
            <li><a href="#" class="tip" title="Retailers"><span class="icon-signal"></span></a></li>
            <li><a href="#" class="tip" title="Last comments"><span class="icon-comment"></span></a></li>
        </ul>
    </div>

    <div class="button">
        <a href="#">
            <span class="icomg-user2"></span>
            <span class="text">Users Actions</span>
        </a>
        <ul class="sub">
            <li><a href="users.html" class="tip" title="Show list"><span class="icon-th-list"></span></a></li>
            <li><a href="ui.html" class="tip" title="Add new"><span class="icon-plus"></span></a></li>
            <li><a href="#" class="tip" title="Registrations"><span class="icon-ok"></span></a></li>
            <li><a href="#" class="tip" title="Send mail"><span class="icon-envelope"></span></a></li>
            <li><a href="#" class="tip" title="Top users"><span class="icon-star"></span></a></li>
            <li><a href="#" class="tip" title="Users activity"><span class="icon-signal"></span></a></li>
            <li><a href="#" class="tip" title="Last comments"><span class="icon-comment"></span></a></li>
        </ul>
    </div>

</div>