<?php
$prod = $this->production ? 'true' : 'false';
$min = $this->production ? 'min.' : '';
$sidebar = (string)$this->placeholder('sidebar');
$this->headLink(
    array(
        'rel'  => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => '/favicon.ico',
    )
);
//$this->headScript()->appendFile("/js/libs/plugins/jquery/jquery-1.9.1.min.js", 'text/javascript');
if ($this->production) {
    $this->headLink()->appendStylesheet("/min/css/backend.min.css");
    $this->headScript()->appendScript("var env = {backend: true, production: true };")
        ->appendFile("/min/js/kickstart.min.js", 'text/javascript');
} else {
    $this->headLink()->appendStylesheet("/css/backend.css");
    $this->headScript()->appendScript("var env = {backend: true, production: false };")
        ->appendFile("/js/app/kickstart.js", 'text/javascript');
}
echo $this->doctype();
?>
<html lang="en">
<head>
    <?php echo $this->headTitle('Synergy Admin - Control Panel');
    echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0');
    echo $this->headLink(); ?><!--[if gt IE 8]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/><![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body>
<?php if (true) { ?>
    <div class="header">
        <?php echo $this->render('layout/virgo/header.phtml'); ?>
    </div>
    <div class="navigation">
        <?php echo $this->render('layout/virgo/navigation.phtml'); ?>
    </div>
    <?php echo $this->render('layout/virgo/breadcrumb.phtml'); ?>
    <?php
    if ($sidebar) {
        ?>
        <div class="content">
            <div class="row-fluid">
                <div class="span9 main-area">
                    <?php echo $this->render('layout/partials/user-message.phtml'); ?>
                    <?php echo $this->content; ?>
                </div>
                <div class="span3">
                    <?php echo $sidebar; ?>
                </div>
            </div>
        </div>
    <?php
    } else {
        ?>
        <div class="content">
            <div class="row-fluid">
                <div class="span12 main-area">
                    <?php echo $this->render('layout/partials/user-message.phtml'); ?>
                    <?php echo $this->content; ?>
                </div>
            </div>
        </div>
    <?php
    }
} else {
    ?>
    <div class="content">
        <?php echo $this->render('layout/partials/user-message.phtml'); ?>
        <?php echo $this->content; ?>
    </div>
<?php
}
echo $this->partial('layout/partials/please-wait.phtml', array('hide' => true));
echo $this->headScript();
?>
</body>
</html>